### ISSUE TITLE
Generate image with two parameters: prompt and image

### ISSUE THREAD

**Issue by PeretoSama** [DedInc/bingart#5]
Hii!
Im  building website (learning purposes), where you will be able to fuse Pokemons using an AI image generation. Bing Image Creator doesn't know all the Pokemons, but if you upload a single image of the two Pokemons side by side, and you prompt something like "fuse these two pokemons" you can get amazing results, instead of just prompting "fuse Pikachu and Charmander".

Your Api Wrapper works very well but the generate image function only has the prompt parameter.
Would you consider to add this feature? 
If not, could you tell me how would you approach this?  Sadly I have 0 web scrapping and python knowledge.

**Comment by DedInc** [comment]
sounds great, but I don't see that kind of functionality here

![image](https://github.com/DedInc/bingart/assets/41906303/23715b92-d3d7-4427-a1fb-7b3afbfd7ee7)

**Comment by DedInc** [comment]
But if you have some other service in mind, then you need to make an SDK for it

**Comment by PeretoSama** [comment]
Yes, im talking about this:
![image](https://github.com/DedInc/bingart/assets/40438743/61a0a389-aaf3-433f-9fb5-812a5886586d)
Here it lets you upload an image but not on the image creator itself .
But on creator it doesnt show the image you have used to make the request.
![image](https://github.com/DedInc/bingart/assets/40438743/9258e3ce-02fd-4455-9155-ea0d55a88bf5)

**Comment by DedInc** [comment]
It doesn't use the picture itself as a reference, it generates a prompt based on it, which does all the magic, so if you want such a cool result you need an API to OpenAI or something else, you can look in the direction of Bing Copilot where you just did it.

Use [sydney ](https://github.com/vsakkas/sydney.py?tab=readme-ov-file#attachment) for it!
